services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/api:/app/api
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - API_ENV=development
      - DB_PATH=/app/data/terminology
      - LOG_LEVEL=INFO
    command: python -m uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
    depends_on:
      - api
    command: npm run dev -- --host 0.0.0.0 --port 3000

networks:
  default:
    driver: bridge